version: '3.8'

services:
  web:
    build: ./
    volumes:
      - ./:/usr/src/MG_RMS/
    ports:
      - 8000:8000
    image: rms
    container_name: rms_container
    env_file:
      - ./.env.dev
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
