# Generated by Django 4.1.7 on 2023-04-11 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0003_alter_dishrestaurantmenuentry_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishrestaurantmenuentry',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Name must be at least 2 characters long.')]),
        ),
        migrations.AlterField(
            model_name='dishrestaurantmenuentry',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0, 'Price cannot be negative.')]),
        ),
        migrations.AlterField(
            model_name='drinkrestaurantmenuentry',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Name must be at least 2 characters long.')]),
        ),
        migrations.AlterField(
            model_name='drinkrestaurantmenuentry',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(0, 'Price cannot be negative.')]),
        ),
    ]
