# Generated by Django 4.1.7 on 2023-04-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0005_drinkrestaurantmenuentry_contains alcohol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkrestaurantmenuentry',
            name='Contains alcohol',
        ),
        migrations.AddField(
            model_name='drinkrestaurantmenuentry',
            name='contains_alcohol',
            field=models.BooleanField(default=False, verbose_name='Contains alcohol'),
        ),
    ]
