# Generated by Django 4.1.7 on 2023-05-18 00:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0006_remove_drinkrestaurantmenuentry_contains alcohol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantMenuEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Name must be at least 2 characters long.')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(limit_value=0.0, message='Price cannot be negative.')])),
            ],
        ),
        migrations.RemoveField(
            model_name='dishrestaurantmenuentry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dishrestaurantmenuentry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dishrestaurantmenuentry',
            name='price',
        ),
        migrations.RemoveField(
            model_name='drinkrestaurantmenuentry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='drinkrestaurantmenuentry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='drinkrestaurantmenuentry',
            name='price',
        ),
        migrations.AddField(
            model_name='dishrestaurantmenuentry',
            name='restaurantmenuentry_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RMS.restaurantmenuentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drinkrestaurantmenuentry',
            name='restaurantmenuentry_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RMS.restaurantmenuentry'),
            preserve_default=False,
        ),
    ]
