# Generated by Django 4.1.7 on 2023-05-17 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0008_restaurantavailability_startendhours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startendhours',
            old_name='end_time',
            new_name='_end_time',
        ),
        migrations.RenameField(
            model_name='startendhours',
            old_name='start_time',
            new_name='_start_time',
        ),
    ]
