# Generated by Django 4.1.7 on 2023-05-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0009_alter_dishrestaurantmenuentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties', models.IntegerField(choices=[(1, 'Near window'), (2, 'Near kitchen'), (3, 'In gard'), (4, 'In bar'), (5, 'Is isolated')])),
            ],
        ),
    ]
