# Generated by Django 4.1.7 on 2023-05-17 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0009_rename_end_time_startendhours__end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startendhours',
            old_name='_end_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='startendhours',
            old_name='_start_time',
            new_name='start_time',
        ),
    ]
