# Generated by Django 4.1.7 on 2023-05-17 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0010_rename__end_time_startendhours_end_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantAvailability',
        ),
    ]
