# Generated by Django 4.1.7 on 2023-05-18 06:32

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0011_delete_restaurantavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, django.db.models.fields.Field),
        ),
    ]
