# Generated by Django 4.1.7 on 2023-06-01 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0012_alter_restauranttable_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Name must be at least 2 characters long.')])),
                ('role', models.IntegerField(choices=[(1, 'Waiter'), (2, 'Dishwasher'), (3, 'Chef'), (4, 'Manager'), (5, 'Cleaner')])),
            ],
        ),
    ]
