# Generated by Django 4.1.7 on 2023-05-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0012_restaurantavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='_availability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RMS.restaurantavailability'),
        ),
    ]
