# Generated by Django 4.1.7 on 2023-06-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0013_manytomanyproperty_remove_restauranttable_properties_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restauranttable',
            name='properties',
        ),
        migrations.DeleteModel(
            name='ManyToManyProperty',
        ),
    ]
