# Generated by Django 4.1.7 on 2023-06-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0013_restaurantworker'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
