# Generated by Django 4.1.7 on 2023-05-24 18:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('RMS', '0013_restaurant__availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='RestaurantMenuEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Name must be at least 2 characters long.')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(limit_value=0.0, message='Price cannot be negative.')])),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('customer_contact_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RMS.contactdata')),
                ('menu_selection', models.ManyToManyField(related_name='models', through='RMS.MenuSelection', to='RMS.restaurantmenuentry')),
            ],
        ),
        migrations.RemoveField(
            model_name='dishrestaurantmenuentry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dishrestaurantmenuentry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dishrestaurantmenuentry',
            name='price',
        ),
        migrations.RemoveField(
            model_name='drinkrestaurantmenuentry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='drinkrestaurantmenuentry',
            name='name',
        ),
        migrations.RemoveField(
            model_name='drinkrestaurantmenuentry',
            name='price',
        ),
        migrations.CreateModel(
            name='RestaurantTableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('startEndHours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RMS.startendhours')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RMS.restauranttable')),
            ],
        ),
        migrations.AddField(
            model_name='menuselection',
            name='menu_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RMS.restaurantmenuentry'),
        ),
        migrations.AddField(
            model_name='menuselection',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RMS.restaurantorder'),
        ),
        migrations.AddField(
            model_name='menuselection',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='dishrestaurantmenuentry',
            name='restaurantmenuentry_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RMS.restaurantmenuentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drinkrestaurantmenuentry',
            name='restaurantmenuentry_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RMS.restaurantmenuentry'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StationaryRestaurantOrder',
            fields=[
                ('restaurantorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RMS.restaurantorder')),
                ('customerComments', models.CharField(max_length=500)),
                ('tableBooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RMS.restauranttablebooking')),
            ],
            bases=('RMS.restaurantorder',),
        ),
        migrations.CreateModel(
            name='DeliveryRestaurantOrder',
            fields=[
                ('restaurantorder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='RMS.restaurantorder')),
                ('deliveryWorkerId', models.CharField(max_length=200)),
                ('customerAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RMS.address')),
                ('deliveryWorkerContactData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RMS.contactdata')),
                ('desiredStartEndHours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RMS.startendhours')),
            ],
            bases=('RMS.restaurantorder',),
        ),
    ]
