# Generated by Django 4.1.7 on 2023-05-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0014_menuselection_restaurantmenuentry_restaurantorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantavailability',
            name='schedule',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
