# Generated by Django 4.1.7 on 2023-06-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0015_restauranttableproperty_restauranttable_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartEndHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('startEndHours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RMS.startendhours')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RMS.restauranttable')),
            ],
        ),
    ]
