# Generated by Django 4.1.7 on 2023-06-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0014_restaurantavailability'),
        ('RMS', '0015_restauranttableproperty_restauranttable_properties'),
    ]

    operations = [
    ]
