# Generated by Django 4.1.7 on 2023-06-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0016_merge_20230611_1612'),
        ('RMS', '0016_startendhours_restauranttablebooking'),
    ]

    operations = [
    ]
