# Generated by Django 4.1.7 on 2023-06-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0017_merge_20230611_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startendhours',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='startendhours',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
