# Generated by Django 4.1.7 on 2023-05-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0018_alter_restaurantavailability_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startendhours',
            name='end_time',
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True)),
        ),
        migrations.AlterField(
            model_name='startendhours',
            name='start_time',
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True)),
        ),
    ]
