# Generated by Django 4.1.7 on 2023-06-14 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0018_alter_startendhours_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('menu_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RMS.restaurantmenuentry')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('customer_contact_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RMS.contactdata')),
                ('menu_selection', models.ManyToManyField(through='RMS.MenuSelection', to='RMS.restaurantmenuentry')),
            ],
        ),
        migrations.AddField(
            model_name='menuselection',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RMS.restaurantorder'),
        ),
    ]
