# Generated by Django 4.1.7 on 2023-06-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0019_menuselection_restaurantorder_menuselection_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantorder',
            name='menu_selection',
            field=models.ManyToManyField(null=True, through='RMS.MenuSelection', to='RMS.restaurantmenuentry'),
        ),
    ]
