# Generated by Django 4.1.7 on 2023-05-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0019_alter_startendhours_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startendhours',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='startendhours',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
