# Generated by Django 4.1.7 on 2023-06-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0019_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantWorkerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(choices=[('waiter', 'waiter'), ('dishwasher', 'dishwasher'), ('chef', 'chef'), ('manager', 'manager'), ('cleaner', 'cleaner'), ('customer_manager', 'customer_manager'), ('delivery_manager', 'delivery_manager'), ('system', 'system')])),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(to='RMS.restaurantworkerrole', verbose_name='list of properties'),
        ),
    ]
