# Generated by Django 4.1.7 on 2023-06-14 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RMS', '0020_restaurantworkerrole_remove_customuser_roles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantworker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='restaurantworker',
            name='role',
        ),
        migrations.AddField(
            model_name='restaurantworker',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantworker',
            name='roles',
            field=models.ManyToManyField(to='RMS.restaurantworkerrole'),
        ),
        migrations.AddField(
            model_name='restaurantworker',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurantworker',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
