# Generated by Django 4.1.7 on 2023-06-14 23:52

import RMS.models.RestaurantWorker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0021_remove_restaurantworker_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantworker',
            name='roles',
        ),
        migrations.DeleteModel(
            name='RestaurantWorkerRole',
        ),
        migrations.AddField(
            model_name='restaurantworker',
            name='roles',
            field=RMS.models.RestaurantWorker.SeparatedValuesField(choices=[('waiter', 'Waiter'), ('dishwasher', 'Dishwasher'), ('chef', 'Chef'), ('manager', 'Manager'), ('cleaner', 'Cleaner'), ('customer_manager', 'Customer Manager'), ('delivery_manager', 'Delivery Manager'), ('system', 'System')], default=0, max_length=64),
            preserve_default=False,
        ),
    ]
