# Generated by Django 4.1.7 on 2023-06-15 00:02

import RMS.models.RestaurantWorker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0022_remove_restaurantworker_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantworker',
            name='roles',
            field=RMS.models.RestaurantWorker.SeparatedValuesField(blank=True, choices=[('waiter', 'Waiter'), ('dishwasher', 'Dishwasher'), ('chef', 'Chef'), ('manager', 'Manager'), ('cleaner', 'Cleaner'), ('customer_manager', 'Customer Manager'), ('delivery_manager', 'Delivery Manager'), ('system', 'System')], max_length=64),
        ),
    ]
