# Generated by Django 4.1.7 on 2023-06-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0024_alter_restaurantworker_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauranttablebooking',
            name='date',
            field=models.DateField(),
        ),
    ]
