# Generated by Django 4.1.7 on 2023-06-15 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0019_menuselection_restaurantorder'),
        ('RMS', '0025_alter_restauranttablebooking_date'),
    ]

    operations = [
    ]
